apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home-pvc
  namespace: jenkins-prod
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/component: controller
    environment: production
    team: platform-sre
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: premium-rwo
  resources:
    requests:
      storage: 100Gi
