apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-controller
  namespace: jenkins-prod
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/component: controller
    environment: production
    team: platform-sre
  annotations:
    iam.gke.io/gcp-service-account: jenkins-controller@enterprise-platform-prod.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-agent
  namespace: jenkins-agents
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/component: agent
    environment: production
    team: platform-sre
  annotations:
    iam.gke.io/gcp-service-account: jenkins-agent@enterprise-platform-prod.iam.gserviceaccount.com
